[package]
name = "monkey-rs"
version = "0.1.0"
edition = "2021"
authors = ["wzid <me@cameron.rs>"]


[[bin]]
name = "monkey-rs"
path = "src/bin/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]