[package]
name = "monkey-rs"
version = "0.1.0"
edition = "2021"
authors = ["wzid <me@cameron.rs>"]

[lib]
name = "monkey_lib"
path = "lib/lib.rs"

[[bin]]
name = "monkey-rs"
path = "src/main.rs"


[dependencies]
clap = { version = "4.3.3", features = ["derive"] }